[supervisord]
nodaemon=true
logfile=%(ENV_APP_LOGS)s/supervisord.log
pidfile=%(ENV_APP_HOME)s/supervisord.pid
loglevel=info
user=root   ; 如果确实要以 root 运行，可以加上避免警告

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/cron.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true

[program:rsyslog]
command=/usr/local/bin/start_rsyslog.sh
user=root
startsecs=2
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/rsyslog.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true

[program:healthcheck]
command=python3 -m gunicorn --worker-class gthread -w 1 --threads 4 --timeout 120 --max-requests 1000 --max-requests-jitter 50 -b 0.0.0.0:7860 app:app --chdir %(ENV_APP_HOME)s
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/app.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true

[program:httpd]
command=busybox httpd -f -p 8080 -h %(ENV_APP_HOME)s/navpage
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/httpd.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true

[program:ttyd]
command=ttyd --writable -p 7681 -c %(ENV_APP_USERNAME)s:%(ENV_APP_PASSWORD)s bash
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/ttyd.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true

[program:seven]
command=%(ENV_APP_HOME)s/seven.sh
user=%(ENV_APP_USER)s
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/seven.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
