[supervisord]
nodaemon=true
logfile=%(ENV_APP_LOGS)s/supervisord.log
pidfile=%(ENV_APP_HOME)s/supervisord.pid
loglevel=info
user=root   ; 如果确实要以 root 运行，可以加上避免警告

[program:xray]
command=./xray run -config config.json
directory=%(ENV_APP_HOME)s
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/xray.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
