[supervisord]
nodaemon=true
logfile=%(ENV_APP_LOGS)s/supervisord.log
pidfile=%(ENV_APP_HOME)s/supervisord.pid
loglevel=info
user=appuser   ; 如果确实要以 root 运行，可以加上避免警告

[program:crond]
command=/usr/sbin/crond -f -l 8 -c /etc/crontabs
autostart=true
autorestart=true
user=appuser
stdout_logfile=%(ENV_APP_LOGS)s/cron.log
stderr_logfile=%(ENV_APP_LOGS)s/cron.err
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:xray]
command=./xray run -config config.json
directory=%(ENV_APP_HOME)s
autostart=true
autorestart=true
stdout_logfile=%(ENV_APP_LOGS)s/xray.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true
user=appuser

[inet_http_server]
port=0.0.0.0:2779
username=admin
password=admin123

[supervisorctl]
serverurl=http://127.0.0.1:2779
username=admin
password=admin123

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
